version: '3.8'
services:
  postgres_db:
    image: postgres:13.5
    container_name: FunctionallyFit
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
volumes:
  postgres_db:
    driver: local
